import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "DesignForge Site",
  description: "Generated by DesignForge.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
